### ISSUE TITLE
Failed to OPEN after startup

### ISSUE THREAD

**Issue by Baoyx007** [chennlang/js-analyzer#12]
**Describe the bug**
it's looks like it unable to access the project’s JS resources 

**To Reproduce**
1. yarn global add js-analyzer
2. js-analyzer --root ./

**Screenshots**
<img width="300" alt="image" src="https://github.com/chennlang/js-analyzer/assets/1262198/b9b53a1e-8691-4145-8904-784417dd08cb">

<img width="783" alt="image" src="https://github.com/chennlang/js-analyzer/assets/1262198/4c4d40d8-2077-4fb0-965f-8fd4cb7d68aa">

**js-analyzer**
no configuration provided

**Comment by chennlang** [comment]
@Baoyx007 The architecture has been adjusted, please upgrade to > = v2.2.6
