### ISSUE TITLE
运行 `js-analyzer --root ./` 命令报错

### ISSUE THREAD

**Issue by DBAAZzz** [chennlang/js-analyzer#14]
**Screenshots**
![image](https://github.com/chennlang/js-analyzer/assets/41032629/8ea0ffbb-f4cd-436f-a0d4-3049dc5a0b15)

请问大佬这个报错该如何解决呀，版本是2.3.0

**Comment by chennlang** [comment]
@DBAAZzz 抱歉，可能是之前改动影响了，请更新到 >= 2.3.1 再试试
