### ISSUE TITLE
vue 模板解析

### ISSUE THREAD

**Issue by mannymu** [chennlang/js-analyzer#17]
<img width="339" alt="image" src="https://github.com/user-attachments/assets/6897a0f4-20af-4f79-9073-dfe7303ee4e9">

针对这类vue模板写法，无法正确解析依赖路径

**Comment by mannymu** [comment]
<img width="171" alt="image" src="https://github.com/user-attachments/assets/8338df45-8197-4f32-8d27-6389441899b7">

另外多个 style 块，解析依赖只会有最后一块的值，错误代码在：
<img width="761" alt="image" src="https://github.com/user-attachments/assets/df36348a-88b7-4630-b74d-20a679b0585e">

**Comment by chennlang** [comment]
fixed in v2.4.0
