### ISSUE TITLE
在项目根目录启动后没有任何文件被分析

### ISSUE THREAD

**Issue by RaHsu** [chennlang/js-analyzer#20]
**Describe the bug**
按照文档安装，在项目根目录启动后，点击进入到报告页面，没有任何文件

**To Reproduce**
按照文档安装，在项目根目录启动后，点击进入到报告页面，没有任何文件

**Expected behavior**
出现项目文件

**Screenshots**
![image](https://github.com/user-attachments/assets/ff83843f-c726-41f0-afed-bd468374a732)
![image](https://github.com/user-attachments/assets/d4dcb538-324c-4d42-bb02-ad532c955344)

**js-analyzer**
没有使用配置文件

**Comment by chennlang** [comment]
@RaHsu 你好，是在前端项目的根目录启动的吗？

**Comment by RaHsu** [comment]
是的，是在根目录启动的

**Comment by chennlang** [comment]
没看到明显的报错信息，方便发下项目的目录层级信息吗？或者有一个可复现的最小项目 demo，这样能方便快速定位

**Comment by wkylin** [comment]
我来一个demo吧，https://github.com/wkylin/pro-react-admin

**Comment by wkylin** [comment]
> 没看到明显的报错信息，方便发下项目的目录层级信息吗？或者有一个可复现的最小项目 demo，这样能方便快速定位
看这个项目： https://github.com/wkylin/pro-react-admin

**Comment by chennlang** [comment]
> 我来一个demo吧，https://github.com/wkylin/pro-react-admin

我下载后试了一下，应该没啥问题，你们确认一下用的版本呢，最新的是 v2.5.0,可以使用 `js-analyzer -v` 查看版本
![image](https://github.com/user-attachments/assets/f365bb9d-c3e2-4a14-b6a0-eff9e211b6c2)

**Comment by chennlang** [comment]
> 我来一个demo吧，https://github.com/wkylin/pro-react-admin

还是按照上面的示例项目，通过局部安装，配置完别名后，关系图会更完整
![image](https://github.com/user-attachments/assets/817b7ae0-527e-4bae-bcab-c150a2c64619)

![image](https://github.com/user-attachments/assets/9cba422c-f589-4e00-ad76-e58a8864dd9a)

**Comment by wkylin** [comment]
需要其他的配置么？还是说配置路径 不对，本地还是无法看到...
![image](https://github.com/user-attachments/assets/7feb2c66-9a91-456f-a0fd-e4df2e0a1f2e)

**Comment by wkylin** [comment]
![image](https://github.com/user-attachments/assets/9e52e3c9-016e-4281-b11f-89ff0d1d3917)

**Comment by chennlang** [comment]
@wkylin 你使用配置文件的方式试试呢
https://github.com/chennlang/js-analyzer#configuration-file

**Comment by wkylin** [comment]
运行命令后直接把配置文件本地打开了, 8088端口服务没有启起来...
![image](https://github.com/user-attachments/assets/6e37ef1d-407e-4d76-b89d-49c88163b4b6)

**Comment by chennlang** [comment]
@wkylin  root 要用绝对路径

**Comment by wkylin** [comment]
> @wkylin root 要用绝对路径

root: "C:\wui\pro-react\pro-react-admin" 依然还是打开了配置文件

**Comment by wkylin** [comment]
root: "/wui/pro-react/pro-react-admin" 还是不行
和系统有关系？？windows or mac ??

**Comment by chennlang** [comment]
有可能.... 我用的 mac, windows 确实没测过，我测一下~

**Comment by FireworksBear** [comment]
windos不行的，需要改下代码

**Comment by FireworksBear** [comment]
package/core/src/index.ts    resolePath方法   
修改下路径/和\的问题就好了，做一下不同平台的适配就行了，我改完windows平台就没问题了

**Comment by FireworksBear** [comment]
@chennlang

**Comment by chennlang** [comment]
@FireworksBear  好的，非常感谢，我尽快修复，也欢迎各位大佬发现问题直接提 PR
> 最近工作有点忙...

**Comment by chennlang** [comment]
@wkylin @RaHsu @FireworksBear  已兼容 windows 系统，请升级到 v2.5.1 ~
```shell
npm remove @js-analyzer/server -g
npm install @js-analyzer/server -g
```
