### ISSUE TITLE
无法看到当前文件引用的文件，只能看到被引用

### ISSUE THREAD

**Issue by verehu** [chennlang/js-analyzer#22]
**Describe the bug**
无法看到当前文件引用的文件，只能看到被引用

**To Reproduce**
正常跑项目

**Expected behavior**
期望除了看到文件被引用数量外，还有该文件导入了多少数量的分析

**Screenshots**
无

**js-analyzer**
please attach the startup configuration file of js-analyzer

**Comment by chennlang** [comment]
@verehu 切换一下视图模式，就能看到了
![image](https://github.com/user-attachments/assets/4033377c-c34d-4d96-b518-c84dfcf153d5)
![image](https://github.com/user-attachments/assets/2b484087-1b11-4754-996e-0b4de1350201)
