### ISSUE TITLE
详情页面中引用数量不准确

### ISSUE THREAD

**Issue by FireworksBear** [chennlang/js-analyzer#24]
随便点击一个点，弹出详情页面，页面中的引用数量是有问题的，第一次点没问题，关掉详情后，再点击其他点，引用数量显示的还是上一个点的引用数量，再点开相同的点，引用数量才会正确。

**Comment by chennlang** [comment]
好的，正在跟进

**Comment by chennlang** [comment]
非常感谢您的问题反馈，v2.6.2 已修复~
