### ISSUE TITLE
执行命令打开页面报错

### ISSUE THREAD

**Issue by keyzf** [chennlang/js-analyzer#3]
js-analyzer --config ./js-analyzer.js    
生成的文件目录跟名称是错误的，比如应该是src/data目录，但是弄的是srdat
![image](https://github.com/chennlang/js-analyzer/assets/5309123/f9227113-0d21-4aa8-b786-7250300c412c)

**Comment by chennlang** [comment]
@keyzf 你好，方便贴上 js-analyzer.js 文件吗？

**Comment by chennlang** [comment]
没办法复现，猜测有可能是别名配置的不正确，请检查配置，有问题再反馈，先关闭了。
