### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by gt-wangqiaoling01** [chennlang/js-analyzer#33]
通过 npm create vite@latest 命令新建的项目
技术栈：vue3 + ts
运行 npm run js-analyzer 报错如下：
<img width="729" alt="image" src="https://github.com/user-attachments/assets/5f137553-c7fa-43d6-aa65-f80d8e5a0769">

**Comment by gt-wangqiaoling01** [comment]
<img width="273" alt="image" src="https://github.com/user-attachments/assets/de785a4f-0e61-4789-8499-fb7969fd9817">
这个包是不是有问题？

**Comment by chennlang** [comment]
参考 #32 ，需要更新一下
```shell
npm update @js-analyzer/server -g
```
