### ISSUE TITLE
feature: 支持更细粒度（函数、变量）的依赖分析

### ISSUE THREAD

**Issue by hughfenghen** [chennlang/js-analyzer#4]
hello，是否考虑支持更细粒度（函数、变量）的依赖分析？

我曾阅读开源项目源码的时候，期望有类似的工具（vscode 、浏览器插件）用于辅助阅读陌生项目源码

比如，选中一个变量或函数，即可视化展示该函数引用的调用者（依赖）、该函数调用（引用）的其他函数

**Comment by chennlang** [comment]
> hello，是否考虑支持更细粒度（函数、变量）的依赖分析？
> 
> 我曾阅读开源项目源码的时候，期望有类似的工具（vscode 、浏览器插件）用于辅助阅读陌生项目源码
> 
> 比如，选中一个变量或函数，即可视化展示该函数引用的调用者（依赖）、该函数调用（引用）的其他函数

你好，这个功能已经实现了，点开单个文件的详情，可以看到里面所有导出变量的引用信息，还可以跳转到引用文件，示例：
![image](https://github.com/chennlang/js-analyzer/assets/41711206/fb31e201-9965-40bb-b646-2cb59488af98)

**Comment by chennlang** [comment]
如果还有任何疑问可以提新的 issue，这个 issue 我先关闭了

**Comment by hughfenghen** [comment]
感谢回复
