### ISSUE TITLE
jsx 的引用无法被识别到

### ISSUE THREAD

**Issue by hyj111** [chennlang/js-analyzer#5]
<img width="919" alt="image" src="https://github.com/chennlang/js-analyzer/assets/52519418/eadfb727-be42-4522-9a75-782d60757253">

![image](https://github.com/chennlang/js-analyzer/assets/52519418/52bdfb2c-a1de-4efd-8576-34879c37d132)

**Comment by hyj111** [comment]
https://github.com/hyj111/js-analyze-test 复现的例子

**Comment by hyj111** [comment]
还有使用相对路径分析时候，关系图列表名称啥的会错乱
<img width="479" alt="image" src="https://github.com/chennlang/js-analyzer/assets/52519418/3c6b2b0f-4287-4b2e-9885-b17abcdc5c80">

**Comment by chennlang** [comment]
你好，原因是 README 给出的配置信息有错， 是 `.jsx` ,之前写成了 `jsx`, 已更新文档
![image](https://github.com/chennlang/js-analyzer/assets/41711206/b087299d-cd30-440a-9752-568b0256ac7e)

**Comment by chennlang** [comment]
> 还有使用相对路径分析时候，关系图列表名称啥的会错乱 <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/52519418/308831183-3c6b2b0f-4287-4b2e-9885-b17abcdc5c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzAyNTEsIm5iZiI6MTcxMTA2OTk1MSwicGF0aCI6Ii81MjUxOTQxOC8zMDg4MzExODMtM2M2YjJiMGYtNDI4Ny00YjJlLTk4ODUtYjE3YWJjZGM1YzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAxMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZjZhMzk3MWJmNTc3ODNlMTRkNzZhODg5OWQ0MmM1YjNiM2IxOWZjMTc5NzhlNzAxMTA3Njg5MWYyYTIzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0Mxr9ovCeFXYgDvYNb5jAupOxEkJHysYjMsHGnyNQU">

这里建议用全路径,或者这么写 
`path.resolve(__dirname, "./")`
