### ISSUE TITLE
import使用相对路径不会被计算入依赖

### ISSUE THREAD

**Issue by 1057891494** [chennlang/js-analyzer#8]
![image](https://github.com/chennlang/js-analyzer/assets/30371200/45d6ab1c-b3f1-4395-86e2-10ff9de0e074)

![image](https://github.com/chennlang/js-analyzer/assets/30371200/033f6d88-5034-4760-b1b0-c3f200cc8d58)

**Comment by 1057891494** [comment]
抱歉，上述问题是我alias设置有问题导致

**Comment by 1057891494** [comment]
但是App.vue没有被计算入依赖
![image](https://github.com/chennlang/js-analyzer/assets/30371200/8434fae6-ef3c-480b-a10d-85c3fcb609a1)

**Comment by 1057891494** [comment]
![image](https://github.com/chennlang/js-analyzer/assets/30371200/22b54721-6114-4cc3-99bf-56d64968320d)

**Comment by chennlang** [comment]
> 但是App.vue没有被计算入依赖 ![image](https://private-user-images.githubusercontent.com/30371200/322479732-8434fae6-ef3c-480b-a10d-85c3fcb609a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzY3ODYsIm5iZiI6MTcxNDI3NjQ4NiwicGF0aCI6Ii8zMDM3MTIwMC8zMjI0Nzk3MzItODQzNGZhZTYtZWYzYy00ODBiLWExMGQtODVjM2ZjYjYwOWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAzNTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MWZjNmYzYmIxNjQxMmRiNmU2YTFiNTk0MTdmOGM1OGY5ZWEwYmI4MWMwNjZkZTdmNDY2NjVkZjczYWJiOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xvKblW3EgWCDavxRt9_52ZH9HrQg2aBAgTSdUgj4OKk)

你好，方便贴一下配置文件吗？

**Comment by chennlang** [comment]
![image](https://github.com/chennlang/js-analyzer/assets/41711206/1ae463c9-5ddd-4a8d-942c-4fcf47244d45)
抱歉给你带来误解，上面的视图默认是“被依赖视图”，所以显示为 “0”，切换成 “依赖视图“ 才能看到依赖的文件
